name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go: [ '1.20', '1.21' ]
        
    name: Go ${{ matrix.go }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.55.2

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      
    - name: Send coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.txt
        flag-name: Go-${{ matrix.go }}
        parallel: true

  check-coverage:
    name: Check coverage
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
